### ISSUE TITLE
title missing for DEU026

### ISSUE THREAD

**Issue by jberenike** [distantreading/WG1#37]
should be "Auch Einer. Eine Reisebekanntschaft. Zweiter Band" 

see http://www.deutschestextarchiv.de/book/show/vischer_auch02_1879

**Comment by jberenike** [comment]
just noticed that the DEU034 is part 1 ("Band 1") of the same publication. Do we want to include these as two separate entries?

**Comment by CarolinOdebrecht** [comment]
In my view, your questions addresses two issues: first the text selection of ELTeC-deu and second what do we do in the title study. 
First: I think, two parts which are separately published can be included in the collection in general. If these two part can be interpreted as a serial publication of one novel, the question should go to the contributors two ELTeC-deu. Maybe, this help to clarify decisions or change necessary things.
Second: Include the missing title in the table (sometimes there is something wrong in the TEI XML file that causes display problems in the summary  page https://distantreading.github.io/ELTeC/index.html. In any case, include both titles in the annotation. Is it easier to remove a data point afters as to add one.

**Comment by jberenike** [comment]
yes, I throught I address the issue generally, so that contributors to ELTeC-deu can take a look.
for titles-study I just included the title as found in DTA; will include both 1 and 2 as instances of serial pub (pending verdict by contr. of ELTeC-deu)

**Comment by CarolinOdebrecht** [comment]
As this repository is focused on WG1 members, Fotis and Leonard might missed this issue. 
You could move (or copy) the issue to ELTeC-deu.

**Comment by lb42** [comment]
I just noticed that several texts in ELTeC-deu are invalid against the current schema ("print_source" is not the same as "printSource") which doesn't help. Unfortunately I didn't notice this when I did the last update to the repo in March.
FWIW, I think the two volumes of this work should be treated as a single text, since that is what we do in other repositories.

**Comment by lb42** [comment]
p.s. The title doesn't appear in the summary listing because it is incorrectly formatted in the source (no ": ELTeC ausgabe") I have fixed this, but not the other, more serious, issues raised on this ticket.

**Comment by dianamsmpsantos** [comment]
Dear all
I am not sure why I am getting these messages since I am (sadly) not
involved in this title study, but I do have some opinions on some things
(and have also done a light title study for Portuguese for another paper),
so:
1) I am not happy with translation into English of titles, not with
translation into "bad English" either
I would suggest that whatever features you wanted to count, you asked the
people of that language/culture. Feminine names, reference to places, etc.
2) I wonder what example Ioana is mentioning of Portuguese titles. Person
names that include places? I cannot remember that any of the Portuguese
titles have that...
3) For the Portuguese collection, works published in several volumes have
been included as ONE text (otherwise we would not have enough long texts :)
Best
Diana



Lou <notifications@github.com> escreveu no dia quinta, 28/05/2020 à(s)
16:43:

**Comment by CarolinOdebrecht** [comment]
Dear Diana,
see https://github.com/distantreading/WG1/issues/34#issuecomment-629185034 for more explanations for the title study. 
Warm greetings,
Carolin

**Comment by jberenike** [comment]
> As this repository is focused on WG1 members, Fotis and Leonard might missed this issue.
> You could move (or copy) the issue to ELTeC-deu.

can you give me the URL? :-)

**Comment by CarolinOdebrecht** [comment]
https://github.com/COST-ELTeC/ELTeC-deu 
:-)

**Comment by jberenike** [comment]
ok. DOne: https://github.com/COST-ELTeC/ELTeC-deu/issues/7
