### ISSUE TITLE
titleStudy: additional cells in spreadsheet (person, place)?

### ISSUE THREAD

**Issue by jberenike** [distantreading/WG1#38]
Shouldn’t we just have all relevant cells duplicated for further entities falling into the cats: place, person? 
We do this for „otherEntity“: https://github.com/distantreading/WG1/blob/master/titlePilotStudy/data/dataPreparation.md 

Here's what I encountered:
Amoung the titles of DEU, in addition to multiple persons (personII) and other entities (otherEntitiesII), I found multiple place names — Arkansas, Amerika:

"Die Regulatoren in Arkansas. Aus dem Waldleben Amerikas"
"The regulators in Arkansas. From the Forest Life of America“ (deepL)

What I did for the second „place entity“ (Amerika) was to add columns to the right of the spreadsheet row, like below. 

placeEntityII		placeAttributionII		placeDeterminerII		placeSyntaxI

As you discussed for person, I added the second place *lexeme* (actually: the lemma, in lower case, without inflection!) in the cell „placeEntity“ after the first place lemma: "arkansas, amerika". 

For placeAttribution and placeDeterminer, I entered info just for the first instance of place (here: arkansas). 
I think we should add cells for all places and persons.

**Comment by galleron** [comment]
I agree with you. We'd better add columns for each person, place or other entity. It allows a finer description of the titles, even if it is cumbersome as the number of the columns is greatly multiplied since we have, in each case, to add columns for determiners, attributes and for syntactic/ semantic roles too. But since we do not have to do this for all titles, I daresay it remains manageable. I update the guidelines in this sense.

**Comment by jberenike** [comment]
thxs!
