### ISSUE TITLE
Sampling criteria : please let's not use the word "level" here too

### ISSUE THREAD

**Issue by lb42** [distantreading/WG1#4]
It is confusing to have "level"s of encoding and also "level"s of sampling. The latter are not levels at all, they are just different criteria: level 1 is the  "eligibility" criterion; "level 2" is the "composition" criterion. Note also that "eligibility" applies to an individual text, so can be determined immediately, whereas "composition" applies to the effect of a text on the balance of the collection over all, and therefore cannot be determined immediately. It's not clear how, when, or by whom, the criterion should be evaluated!
I suggest that (for workflow purposes at least), we make a further "documentation" criterion : does the text header contain the information required to determine its effect on the composition of the collection? i.e. do we know authorship, length, publication place, etc.

**Comment by CarolinOdebrecht** [comment]
We can just remove the "level" in the document (already done). I just copied the names from the framapad notes. 
We defined a sampling team, which should support the sampling process. At the moment, Carolin, Pieter and Diana are in the team. Maybe, we could ask more WG members to join!
As for the workflow: I think it is crucial that we know all required metadata of a text candidate for ELTeC in advance. There should be a kind of formal check (e.g. by the sampling support team) if a text can be included in ELTeC according to the sampling guidelines and the current composition of the language collection (otherwise we can add the text in the ELTeC extension corpus).

**Comment by lb42** [comment]
I could probably modify the eltec0 or 1 schema so that a document which doesn't include the required metadata would not be valid. And I'm happy to joing the "sampling team" as well.

What is this "ELTeC extension corpus" for?  Is it just to make it easy for people who don't want to produce texts that conform with our guidelines? If so, doesn't providing it suggest we are not really serious about the constraints we're proposing to use?

**Comment by CarolinOdebrecht** [comment]
Modifying the encoding schema in this way seems to be is a great idea! 
I also added you to the sampling team (cf. wiki page workflow). 

As for the ELTeC-Extension Corpus: With such an extension corpus, we can also collect texts which don't fit the balancing criteria, e.g., we already have enough non-canonical texts in a certain language collection. All texts in the extension corpus must be encoded in the same way(s) as the texts in the ELTeC-Corpus.
